from opentrons import protocol_api

metadata = {"protocolName": "protocol_02", "author": "generated"}
requirements = {"robotType": "Flex", "apiLevel": "2.20"}


def run(protocol: protocol_api.ProtocolContext):
    falcon_tube = protocol.load_labware("opentrons_96_wellplate_200ul_pcr_full_skirt", "A1")
    dilution_tube = protocol.load_labware("opentrons_24_tuberack_generic_2ml_screwcap", "A2")
    master_mix_plate = protocol.load_labware("opentrons_96_wellplate_200ul_pcr_full_skirt", "B1")
    dna_sample_plate = protocol.load_labware("corning_96_wellplate_360ul_flat", "B2")
    tiprack_1 = protocol.load_labware("opentrons_flex_96_tiprack_50ul", "B3")
    tiprack_2 = protocol.load_labware("opentrons_flex_96_tiprack_50ul", "C1")
    tiprack_3 = protocol.load_labware("opentrons_flex_96_tiprack_50ul", "C2")
    protocol.load_trash_bin("A3")
    pipette = protocol.load_instrument("flex_1channel_50", "left", tip_racks=[tiprack_1, tiprack_2, tiprack_3])

    # SKIPPED step 0: missing volume or destination
    pipette.transfer(297, dilution_tube["A1"], dilution_tube["A1"])
    pipette.transfer(3, dilution_tube["A1"], dilution_tube["A1"])
    # step 3: mix (vortex/manual, not automated)
    pipette.transfer(250, dilution_tube["A1"], falcon_tube["A1"])
    pipette.transfer(100, falcon_tube["A1"], falcon_tube["A1"])
    pipette.transfer(100, falcon_tube["A1"], falcon_tube["A1"])
    pipette.transfer(1000, falcon_tube["A1"], falcon_tube["A1"])
    # step 8: mix (vortex/manual, not automated)
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A1"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A2"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A3"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A4"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A5"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A6"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A7"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A8"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A9"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A10"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A11"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["A12"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B1"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B2"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B3"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B4"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B5"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B6"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B7"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B8"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B9"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B10"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B11"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["B12"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C1"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C2"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C3"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C4"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C5"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C6"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C7"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C8"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C9"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C10"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C11"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["C12"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D1"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D2"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D3"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D4"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D5"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D6"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D7"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D8"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D9"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D10"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D11"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["D12"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E1"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E2"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E3"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E4"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E5"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E6"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E7"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E8"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E9"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E10"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E11"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["E12"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F1"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F2"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F3"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F4"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F5"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F6"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F7"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F8"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F9"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F10"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F11"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["F12"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G1"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G2"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G3"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G4"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G5"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G6"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G7"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G8"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G9"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G10"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G11"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["G12"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H1"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H2"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H3"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H4"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H5"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H6"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H7"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H8"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H9"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H10"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H11"])
    pipette.transfer(23, falcon_tube["A1"], master_mix_plate["H12"])
    # EXTERNAL step 105: Centrifuge / Vortex -- Thaw and spin down the extracted DNA sample plate to ensure samples are fully dissolved and collected at the bottom of wells.
    protocol.pause(
        "Manual step: Centrifuge / Vortex. Resume when complete."
    )
    pipette.transfer(2, dna_sample_plate["A1"], master_mix_plate["A1"])
    pipette.transfer(2, dna_sample_plate["A2"], master_mix_plate["A2"])
    pipette.transfer(2, dna_sample_plate["A3"], master_mix_plate["A3"])
    pipette.transfer(2, dna_sample_plate["A4"], master_mix_plate["A4"])
    pipette.transfer(2, dna_sample_plate["A5"], master_mix_plate["A5"])
    pipette.transfer(2, dna_sample_plate["A6"], master_mix_plate["A6"])
    pipette.transfer(2, dna_sample_plate["A7"], master_mix_plate["A7"])
    pipette.transfer(2, dna_sample_plate["A8"], master_mix_plate["A8"])
    pipette.transfer(2, dna_sample_plate["A9"], master_mix_plate["A9"])
    pipette.transfer(2, dna_sample_plate["A10"], master_mix_plate["A10"])
    pipette.transfer(2, dna_sample_plate["A11"], master_mix_plate["A11"])
    pipette.transfer(2, dna_sample_plate["A12"], master_mix_plate["A12"])
    pipette.transfer(2, dna_sample_plate["B1"], master_mix_plate["B1"])
    pipette.transfer(2, dna_sample_plate["B2"], master_mix_plate["B2"])
    pipette.transfer(2, dna_sample_plate["B3"], master_mix_plate["B3"])
    pipette.transfer(2, dna_sample_plate["B4"], master_mix_plate["B4"])
    pipette.transfer(2, dna_sample_plate["B5"], master_mix_plate["B5"])
    pipette.transfer(2, dna_sample_plate["B6"], master_mix_plate["B6"])
    pipette.transfer(2, dna_sample_plate["B7"], master_mix_plate["B7"])
    pipette.transfer(2, dna_sample_plate["B8"], master_mix_plate["B8"])
    pipette.transfer(2, dna_sample_plate["B9"], master_mix_plate["B9"])
    pipette.transfer(2, dna_sample_plate["B10"], master_mix_plate["B10"])
    pipette.transfer(2, dna_sample_plate["B11"], master_mix_plate["B11"])
    pipette.transfer(2, dna_sample_plate["B12"], master_mix_plate["B12"])
    pipette.transfer(2, dna_sample_plate["C1"], master_mix_plate["C1"])
    pipette.transfer(2, dna_sample_plate["C2"], master_mix_plate["C2"])
    pipette.transfer(2, dna_sample_plate["C3"], master_mix_plate["C3"])
    pipette.transfer(2, dna_sample_plate["C4"], master_mix_plate["C4"])
    pipette.transfer(2, dna_sample_plate["C5"], master_mix_plate["C5"])
    pipette.transfer(2, dna_sample_plate["C6"], master_mix_plate["C6"])
    pipette.transfer(2, dna_sample_plate["C7"], master_mix_plate["C7"])
    pipette.transfer(2, dna_sample_plate["C8"], master_mix_plate["C8"])
    pipette.transfer(2, dna_sample_plate["C9"], master_mix_plate["C9"])
    pipette.transfer(2, dna_sample_plate["C10"], master_mix_plate["C10"])
    pipette.transfer(2, dna_sample_plate["C11"], master_mix_plate["C11"])
    pipette.transfer(2, dna_sample_plate["C12"], master_mix_plate["C12"])
    pipette.transfer(2, dna_sample_plate["D1"], master_mix_plate["D1"])
    pipette.transfer(2, dna_sample_plate["D2"], master_mix_plate["D2"])
    pipette.transfer(2, dna_sample_plate["D3"], master_mix_plate["D3"])
    pipette.transfer(2, dna_sample_plate["D4"], master_mix_plate["D4"])
    pipette.transfer(2, dna_sample_plate["D5"], master_mix_plate["D5"])
    pipette.transfer(2, dna_sample_plate["D6"], master_mix_plate["D6"])
    pipette.transfer(2, dna_sample_plate["D7"], master_mix_plate["D7"])
    pipette.transfer(2, dna_sample_plate["D8"], master_mix_plate["D8"])
    pipette.transfer(2, dna_sample_plate["D9"], master_mix_plate["D9"])
    pipette.transfer(2, dna_sample_plate["D10"], master_mix_plate["D10"])
    pipette.transfer(2, dna_sample_plate["D11"], master_mix_plate["D11"])
    pipette.transfer(2, dna_sample_plate["D12"], master_mix_plate["D12"])
    pipette.transfer(2, dna_sample_plate["E1"], master_mix_plate["E1"])
    pipette.transfer(2, dna_sample_plate["E2"], master_mix_plate["E2"])
    pipette.transfer(2, dna_sample_plate["E3"], master_mix_plate["E3"])
    pipette.transfer(2, dna_sample_plate["E4"], master_mix_plate["E4"])
    pipette.transfer(2, dna_sample_plate["E5"], master_mix_plate["E5"])
    pipette.transfer(2, dna_sample_plate["E6"], master_mix_plate["E6"])
    pipette.transfer(2, dna_sample_plate["E7"], master_mix_plate["E7"])
    pipette.transfer(2, dna_sample_plate["E8"], master_mix_plate["E8"])
    pipette.transfer(2, dna_sample_plate["E9"], master_mix_plate["E9"])
    pipette.transfer(2, dna_sample_plate["E10"], master_mix_plate["E10"])
    pipette.transfer(2, dna_sample_plate["E11"], master_mix_plate["E11"])
    pipette.transfer(2, dna_sample_plate["E12"], master_mix_plate["E12"])
    pipette.transfer(2, dna_sample_plate["F1"], master_mix_plate["F1"])
    pipette.transfer(2, dna_sample_plate["F2"], master_mix_plate["F2"])
    pipette.transfer(2, dna_sample_plate["F3"], master_mix_plate["F3"])
    pipette.transfer(2, dna_sample_plate["F4"], master_mix_plate["F4"])
    pipette.transfer(2, dna_sample_plate["F5"], master_mix_plate["F5"])
    pipette.transfer(2, dna_sample_plate["F6"], master_mix_plate["F6"])
    pipette.transfer(2, dna_sample_plate["F7"], master_mix_plate["F7"])
    pipette.transfer(2, dna_sample_plate["F8"], master_mix_plate["F8"])
    pipette.transfer(2, dna_sample_plate["F9"], master_mix_plate["F9"])
    pipette.transfer(2, dna_sample_plate["F10"], master_mix_plate["F10"])
    pipette.transfer(2, dna_sample_plate["F11"], master_mix_plate["F11"])
    pipette.transfer(2, dna_sample_plate["F12"], master_mix_plate["F12"])
    pipette.transfer(2, dna_sample_plate["G1"], master_mix_plate["G1"])
    pipette.transfer(2, dna_sample_plate["G2"], master_mix_plate["G2"])
    pipette.transfer(2, dna_sample_plate["G3"], master_mix_plate["G3"])
    pipette.transfer(2, dna_sample_plate["G4"], master_mix_plate["G4"])
    pipette.transfer(2, dna_sample_plate["G5"], master_mix_plate["G5"])
    pipette.transfer(2, dna_sample_plate["G6"], master_mix_plate["G6"])
    pipette.transfer(2, dna_sample_plate["G7"], master_mix_plate["G7"])
    pipette.transfer(2, dna_sample_plate["G8"], master_mix_plate["G8"])
    pipette.transfer(2, dna_sample_plate["G9"], master_mix_plate["G9"])
    pipette.transfer(2, dna_sample_plate["G10"], master_mix_plate["G10"])
    pipette.transfer(2, dna_sample_plate["G11"], master_mix_plate["G11"])
    pipette.transfer(2, dna_sample_plate["G12"], master_mix_plate["G12"])
    pipette.transfer(2, dna_sample_plate["H1"], master_mix_plate["H1"])
    pipette.transfer(2, dna_sample_plate["H2"], master_mix_plate["H2"])
    pipette.transfer(2, dna_sample_plate["H3"], master_mix_plate["H3"])
    pipette.transfer(2, dna_sample_plate["H4"], master_mix_plate["H4"])
    pipette.transfer(2, dna_sample_plate["H5"], master_mix_plate["H5"])
    pipette.transfer(2, dna_sample_plate["H6"], master_mix_plate["H6"])
    pipette.transfer(2, dna_sample_plate["H7"], master_mix_plate["H7"])
    pipette.transfer(2, dna_sample_plate["H8"], master_mix_plate["H8"])
    pipette.transfer(2, dna_sample_plate["H9"], master_mix_plate["H9"])
    pipette.transfer(2, dna_sample_plate["H10"], master_mix_plate["H10"])
    pipette.transfer(2, dna_sample_plate["H11"], master_mix_plate["H11"])
    pipette.transfer(2, dna_sample_plate["H12"], master_mix_plate["H12"])
    # EXTERNAL step 202: Centrifuge -- Seal PCR plate with plastic film and spin down to eliminate bubbles and ensure liquid is at the bottom of each well.
    protocol.pause(
        "Manual step: Centrifuge. Resume when complete."
    )
    # EXTERNAL step 203: BioRad CFX -- Run qPCR using the hsp60 qPCR 25 uL 40-cycle program on the sealed PCR plate.
    protocol.pause(
        "Manual step: BioRad CFX. Resume when complete."
    )
