from opentrons import protocol_api

metadata = {"protocolName": "protocol_01", "author": "generated"}
requirements = {"robotType": "Flex", "apiLevel": "2.20"}


def run(protocol: protocol_api.ProtocolContext):
    spore_stock = protocol.load_labware("nest_12_reservoir_15ml", "A1")
    cytoone_plate = protocol.load_labware("corning_96_wellplate_360ul_flat", "A2")
    media_reservoir = protocol.load_labware("nest_12_reservoir_15ml", "B1")
    water_reservoir = protocol.load_labware("nest_12_reservoir_15ml", "B2")
    tiprack_1 = protocol.load_labware("opentrons_flex_96_tiprack_50ul", "B3")
    tiprack_2 = protocol.load_labware("opentrons_flex_96_tiprack_50ul", "C1")
    protocol.load_trash_bin("A3")
    pipette = protocol.load_instrument("flex_1channel_50", "left", tip_racks=[tiprack_1, tiprack_2])

    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A1"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A2"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A3"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A4"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A5"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A6"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A7"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A8"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A9"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A10"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A11"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["A12"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B1"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B2"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B3"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B4"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B5"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B6"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B7"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B8"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B9"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B10"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B11"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["B12"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C1"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C2"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C3"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C4"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C5"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C6"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C7"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C8"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C9"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C10"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C11"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["C12"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D1"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D2"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D3"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D4"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D5"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D6"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D7"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D8"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D9"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D10"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D11"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["D12"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E1"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E2"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E3"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E4"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E5"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E6"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E7"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E8"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E9"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E10"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E11"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["E12"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F1"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F2"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F3"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F4"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F5"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F6"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F7"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F8"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F9"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F10"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F11"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["F12"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G1"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G2"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G3"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G4"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G5"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G6"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G7"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G8"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G9"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G10"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G11"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["G12"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H1"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H2"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H3"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H4"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H5"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H6"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H7"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H8"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H9"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H10"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H11"])
    pipette.transfer(5, spore_stock["A1"], cytoone_plate["H12"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A1"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A2"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A3"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A4"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A5"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A6"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A7"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A8"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A9"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A10"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A11"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["A12"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B1"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B2"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B3"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B4"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B5"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B6"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B7"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B8"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B9"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B10"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B11"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["B12"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C1"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C2"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C3"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C4"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C5"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C6"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C7"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C8"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C9"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C10"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C11"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["C12"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D1"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D2"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D3"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D4"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D5"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D6"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D7"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D8"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D9"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D10"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D11"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["D12"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E1"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E2"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E3"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E4"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E5"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E6"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E7"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E8"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E9"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E10"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E11"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["E12"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F1"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F2"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F3"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F4"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F5"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F6"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F7"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F8"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F9"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F10"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F11"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["F12"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G1"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G2"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G3"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G4"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G5"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G6"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G7"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G8"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G9"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G10"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G11"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["G12"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H1"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H2"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H3"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H4"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H5"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H6"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H7"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H8"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H9"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H10"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H11"])
    pipette.transfer(195, media_reservoir["A1"], cytoone_plate["H12"])
    # SKIPPED step 192: missing volume or destination
    # SKIPPED step 193: missing volume or destination
    # SKIPPED step 194: missing volume or destination
    # SKIPPED step 195: missing volume or destination
    # SKIPPED step 196: missing volume or destination
    # SKIPPED step 197: missing volume or destination
    # SKIPPED step 198: missing volume or destination
    # SKIPPED step 199: missing volume or destination
    # SKIPPED step 200: missing volume or destination
    # SKIPPED step 201: missing volume or destination
    # SKIPPED step 202: missing volume or destination
    # SKIPPED step 203: missing volume or destination
    # SKIPPED step 204: missing volume or destination
    # SKIPPED step 205: missing volume or destination
    # SKIPPED step 206: missing volume or destination
    # SKIPPED step 207: missing volume or destination
    # SKIPPED step 208: missing volume or destination
    # SKIPPED step 209: missing volume or destination
    # SKIPPED step 210: missing volume or destination
    # SKIPPED step 211: missing volume or destination
    # SKIPPED step 212: missing volume or destination
    # SKIPPED step 213: missing volume or destination
    # SKIPPED step 214: missing volume or destination
    # SKIPPED step 215: missing volume or destination
    # SKIPPED step 216: missing volume or destination
    # SKIPPED step 217: missing volume or destination
    # SKIPPED step 218: missing volume or destination
    # SKIPPED step 219: missing volume or destination
    # SKIPPED step 220: missing volume or destination
    # SKIPPED step 221: missing volume or destination
    # SKIPPED step 222: missing volume or destination
    # SKIPPED step 223: missing volume or destination
    # SKIPPED step 224: missing volume or destination
    # SKIPPED step 225: missing volume or destination
    # SKIPPED step 226: missing volume or destination
    # SKIPPED step 227: missing volume or destination
    # EXTERNAL step 228: Powerwave X-2 plate reader (with KC software) or BioTek platereader -- Incubate plate at 37 °C for 48 hours while measuring OD600 every 10 minutes, starting with a blank reading and preheating before experiment start.
    protocol.pause(
        "Manual step: Powerwave X-2 plate reader (with KC software) or BioTek platereader. Resume when complete."
    )
